# Makefile generated by BNFC.

GHC        = stack ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc
DIR		   = src/Grammar

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : ${DIR}/Abs.hs ${DIR}/Lex.x ${DIR}/Par.y ${DIR}/Print.hs
	-rm ${DIR}/Test.hs

# Rules for building the parser.

${DIR}/Abs.hs ${DIR}/Lex.x ${DIR}/Par.y ${DIR}/Print.hs : Grammar.cf
	bnfc --haskell -d Grammar.cf -o src

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

# Rules for cleaning generated files.

clean :
	-rm -r ${DIR}
