# Makefile generated by BNFC.

GHC        = stack ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Grammar/Abs.hs Grammar/Lex.x Grammar/Par.y Grammar/Print.hs
	-del .\src\Grammar\Test.hs

# Rules for building the parser.

Grammar/Abs.hs Grammar/Lex.x Grammar/Par.y Grammar/Print.hs : Grammar.cf
	bnfc --haskell -d Grammar.cf -o src

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Grammar/Test : Grammar/Abs.hs Grammar/Lex.hs Grammar/Par.hs Grammar/Print.hs
	${GHC} ${GHC_OPTS} $@ 

# Rules for cleaning generated files.

clean :
	-del -f Grammar/*.hi Grammar/*.o Grammar/*.log Grammar/*.aux Grammar/*.dvi

# EOF