name:                micro-c-analyzer
version:             0.1.0.0
github:              "JakuJ/micro-c-analyzer"
license:             BSD3
author:              "Ali El-Madani, Jakub Janaszkiewicz, Daniel Larsen"
maintainer:          "janaszkiewicz.jakub@gmail.com"
copyright:           "2021 Ali El-Madani, Jakub Janaszkiewicz, Daniel Larsen"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/JakuJ/micro-c-analyzer#readme>

dependencies:
- array # required by BNFC
- base >= 4.7 && < 5
- containers
- data-interval
- deque
- extended-reals
- lens
- mtl
- optparse-applicative
- string-interpolate

default-extensions:
- DataKinds
- DeriveDataTypeable
- DeriveGeneric
- DerivingVia
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- ParallelListComp
- RankNTypes
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- ViewPatterns
- QuasiQuotes

ghc-options:
  # profiling
  - -eventlog
  - -fprof-auto
  - -fno-prof-count-entries
  # optimization
  - -O2
  - -flate-dmd-anal
  - -flate-specialise
  # warnings
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  # warnings disabled for the generated grammar modules
  - -Wno-missing-signatures
  - -Wno-orphans
  - -Wno-missing-pattern-synonym-signatures

library:
  source-dirs: src

executables:
  micro-c-analyzer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - micro-c-analyzer

tests:
  micro-c-analyzer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-incomplete-uni-patterns
    - -Wno-orphans
    dependencies:
    - micro-c-analyzer
    - generic-random
    - hspec
    - QuickCheck
    - silently
