name:                micro-c-analyzer
version:             0.1.0.0
github:              "JakuJ/micro-c-analyzer"
license:             BSD3
author:              "Ali El-Madani, Jakub Janaszkiewicz, Daniel Larsen"
maintainer:          "janaszkiewicz.jakub@gmail.com"
copyright:           "2021 Ali El-Madani, Jakub Janaszkiewicz, Daniel Larsen"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/JakuJ/micro-c-analyzer#readme>

dependencies:
- array # required by BNFC
- base >= 4.7 && < 5
- containers
- lens
- mtl

default-extensions:
- DataKinds
- DefaultSignatures
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- ViewPatterns
- DeriveDataTypeable

ghc-options:
  # optimization
  - -flate-dmd-anal
  - -flate-specialise
  # warnings
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  micro-c-analyzer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - micro-c-analyzer

tests:
  micro-c-analyzer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - micro-c-analyzer
    - hspec
